CREATE TABLE "MGCCOP"."NURSE_ELIGIBLE_COURSES" 
 (	"SUBJ" VARCHAR2(20 BYTE), 
"CNUM" VARCHAR2(20 BYTE), 
"CORE_REQ" CHAR(1 CHAR), 
"MAX_AGE" NUMBER(*,0) DEFAULT null
 ) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
STORAGE(INITIAL 131072 NEXT 131072 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "MGCCC" ;

 COMMENT ON COLUMN "MGCCOP"."NURSE_ELIGIBLE_COURSES"."CORE_REQ" IS 'is the course in question a core requirement for consideration in the ranking?';
 COMMENT ON COLUMN "MGCCOP"."NURSE_ELIGIBLE_COURSES"."MAX_AGE" IS 'The maximum age, in months, a course may be to be included in the applicants gpa calculation';